In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display
import awoc

In [22]:
airport_raw = pd.read_csv('https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat', header = None)

In [23]:
airport_raw.columns = ['Airport ID', 'Name', 'City', 'Country', 'IATA', 'ICAO', 'Latitude',
                       'Longitude', 'Altitude', 'Timezone', 'DST', 'time zone', 'Type', 'Source']

In [24]:
airport_raw.head()

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,time zone,Type,Source
0,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,10,U,Pacific/Port_Moresby,airport,OurAirports
1,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,10,U,Pacific/Port_Moresby,airport,OurAirports
2,3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,10,U,Pacific/Port_Moresby,airport,OurAirports
3,4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,10,U,Pacific/Port_Moresby,airport,OurAirports
4,5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,10,U,Pacific/Port_Moresby,airport,OurAirports

In [25]:
rout_raw = pd.read_csv('https://raw.githubusercontent.com/jpatokal/openflights/master/data/routes.dat', header = None)

In [26]:
rout_raw.columns = ['Airline', 'Airline ID', 'Source airport', 'Source airport ID', 'Destination airport',
 'Destination airport ID', 'Codeshare', 'Stops', 'Equipment']

In [27]:
rout_raw.head()

,Airline,Airline ID,Source airport,Source airport ID,Destination airport,Destination airport ID,Codeshare,Stops,Equipment
0,2B,410,AER,2965,KZN,2990,NaN,0,CR2
1,2B,410,ASF,2966,KZN,2990,NaN,0,CR2
2,2B,410,ASF,2966,MRV,2962,NaN,0,CR2
3,2B,410,CEK,2968,KZN,2990,NaN,0,CR2
4,2B,410,CEK,2968,OVB,4078,NaN,0,CR2

# Задание 2

In [30]:
airport_raw[airport_raw['IATA'] == '\\N']

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,time zone,Type,Source
21,22,Winnipeg / St. Andrews Airport,Winnipeg,Canada,\N,CYAV,50.056400,-97.032501,760,-6,A,America/Winnipeg,airport,OurAirports
22,23,Halifax / CFB Shearwater Heliport,Halifax,Canada,\N,CYAW,44.639702,-63.499401,144,-4,A,America/Halifax,airport,OurAirports
43,44,Princeton Airport,Princeton,Canada,\N,CYDC,49.468102,-120.511002,2298,-8,A,America/Vancouver,airport,OurAirports
103,104,Pitt Meadows Airport,Pitt Meadows,Canada,\N,CYPK,49.216099,-122.709999,11,-8,A,America/Vancouver,airport,OurAirports
210,212,Boufarik Airport,Boufarik,Algeria,\N,DAAK,36.545799,2.876110,335,1,N,Africa/Algiers,airport,OurAirports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7692,14105,Kubinka Air Base,Kubinka,Russia,\N,UUMB,55.611695,36.650002,614,\N,\N,\N,airport,OurAirports
7693,14106,Rogachyovo Air Base,Belaya,Russia,\N,ULDA,71.616699,52.478298,272,\N,\N,\N,airport,OurAirports
7694,14107,Ulan-Ude East Airport,Ulan Ude,Russia,\N,XIUW,51.849998,107.737999,1670,\N,\N,\N,airport,OurAirports
7695,14108,Krechevitsy Air Base,Novgorod,Russia,\N,ULLK,58.625000,31.385000,85,\N,\N,\N,airport,OurAirports
7697,14110,Melitopol Air Base,Melitopol,Ukraine,\N,UKDM,46.880001,35.305000,0,\N,\N,\N,airport,OurAirports

### Самые главные, простые и неточные данные - это их отсутвие, в различных колонках (IATA, Timezone, DST, timezone и.т.д) пропущены данные - \N

In [31]:
rout_raw[rout_raw['Source airport'] == rout_raw['Destination airport']]

,Airline,Airline ID,Source airport,Source airport ID,Destination airport,Destination airport ID,Codeshare,Stops,Equipment
33276,IL,10121,PKN,3910,PKN,3910,NaN,0,AT7

### Также имеем проблему одного и тогоже кода IATA  в аэрапорте вылета и в аэропорте прилёта, следовательно самолёт вылетел из одного аэропорта и прилетел в тот же. Чисто технически такое возможно, самолёт мог вылететь и из-за плохих погодных условий вернулся обратно.

In [32]:
airport_raw[airport_raw['IATA'] == 'PNA']

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,time zone,Type,Source
1201,1234,Pamplona Airport,Pamplona,Spain,PNA,LEPP,42.77,-1.64633,1504,1,E,Europe/Madrid,airport,OurAirports

In [33]:
airport_raw[airport_raw['IATA'] == 'HLE']

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,time zone,Type,Source
7400,13180,St. Helena Airport,Longwood,United Kingdom,HLE,FHSH,-15.957725,-5.645943,1017,0,U,\N,airport,OurAirports

### Ещё бывют случаи, такие что указаны неверные координаты аэропорта, то есть город написан один, но по координатам он в другом месте, проще всего это увидеть при выполнении 3-го задания, когда мы будем визуализировать все аэропорты.